---
controller_hosts:
  - name: azure-automation-anchor
    inventory: Azure-Resources
    variables:
      cloud: azure
      automation_account: "{{ azure_automation_account }}"
      runbook_name: "{{ azure_runbook_name }}"

  - name: "{{ aws_ssm_target_instance_id }}"
    inventory: AWS-Resources
    variables:
      cloud: aws
      ssm_document: "{{ aws_ssm_document_name }}"
